name: Deploy main on push

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

env:
  AZURE_WEBAPP_NAME: NotionCMSBlogService 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
      #Run dotnet build and publish: -r linux-x64 
    - name: dotnet build and publish
      run: |
        cd Api
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Api/myapp'