name: Deploy main on push

on:
  push:
    branches:
      - main
      - tashim/feat-1

env:
  AZURE_WEBAPP_NAME: NotionCMSBlogService 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  DOTNET_VERSION: '6.0.x'
  NOTION_VERSION: '2022-06-28'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
      #Run dotnet build and publish: -r linux-x64
    - name: fix packages
      run: |
        cd Api
        dotnet restore
    - name: configigure settings
      run: |
        cd Api
        notion_auth="${{ secrets.NOTION_AUTH }}"
        notion_version="${{ env.NOTION_VERSION }}"
        block_url="${{ secrets.BLOCK_URL}}"
        cat appsettings.json | jq \
        ".NotionSettings.Authorization=\"$notion_auth\" | .NotionSettings.NotionVersion=\"$notion_version\" | .NotionSettings.BlockUrl=\"$block_url\"" \
        > appsettings.new.json
        mv appsettings.new.json Api/appsettings.json
        cat Api/appsettings.json
        echo "app setings file is above"
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      # Deploy to Azure Web apps (you have to specify /Api/myapp)
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Api/myapp'
